<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="WS_ReservationWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/WS_ReservationWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/WS_ReservationWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://wsreservation/">
    <import location="http://localhost:8080/WS_Reservations/WS_Reservation?WSDL" namespace="http://wsreservation/"/>
    <plnk:partnerLinkType name="WS_ReservationLinkType">
        <plnk:role name="WS_ReservationRole" portType="ns:WS_Reservation"/>
    </plnk:partnerLinkType>
</definitions>
